reviewers:
  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    qe:
      - Bischoff
      - elariekerboull
      - ktsamis
      - maximenoel8
      - nodeg
      - orestis87
      - srbarrios
      - vandabarata

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  'testsuite/**/!(*.feature)':
    - qe

options:
  ignore_draft: true
  ignored_keywords:
    - WIP
    - DRAFT
  enable_group_assignment: true
